icon_filename  = 'icon_512.png'

[[links]]
href = 'https://apps.shopify.com/redirectify'
text = 'Install'
external = true
primary = true

[[links]]
href = '/apps/redirectify/docs/general/getting-started-with-redirectify'
text = 'Getting Started'

[[links]]
href = '/apps/redirectify/docs'
text = 'Docs'
